apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingArea
  labels:
    app: parkingArea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingArea
  template:
    metadata:
      labels:
        app: parkingArea
    spec:
      containers:
        - name: parkingArea
          image: username/parkingArea:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5