apiVersion: apps/v1
kind: Deployment
metadata:
  name: parkingGate
  labels:
    app: parkingGate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: parkingGate
  template:
    metadata:
      labels:
        app: parkingGate
    spec:
      containers:
        - name: parkingGate
          image: username/parkingGate:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5