server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: parkingGate
          uri: http://localhost:8081
          predicates:
            - Path=/parkings/** 
        - id: parkingArea
          uri: http://localhost:8082
          predicates:
            - Path=/parkAreas/**, /parkingZoneStatuses/** 
        - id: payment
          uri: http://localhost:8083
          predicates:
            - Path=/payments/** 
        - id: DashBoard
          uri: http://localhost:8084
          predicates:
            - Path= 
        - id: frontend
          uri: http://localhost:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: parkingGate
          uri: http://parkingGate:8080
          predicates:
            - Path=/parkings/** 
        - id: parkingArea
          uri: http://parkingArea:8080
          predicates:
            - Path=/parkAreas/**, /parkingZoneStatuses/** 
        - id: payment
          uri: http://payment:8080
          predicates:
            - Path=/payments/** 
        - id: DashBoard
          uri: http://dashBoard:8080
          predicates:
            - Path= 
        - id: frontend
          uri: http://frontend:8080
          predicates:
            - Path=/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
